name: docker-over-ssh
on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  IMAGE_ID: ghcr.io/${{ github.repository_owner }}/docker-over-ssh-action

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run basic docker info
        uses: ./
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker info
      - name: Test env vars
        uses: ./
        with:
          user: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${FOO}
        env:
          FOO: bar
  build:
    name: Build
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag ${IMAGE_ID}
      - name: GHCR login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          docker tag ${IMAGE_ID} ${IMAGE_ID}:${VERSION}
          docker push ${IMAGE_ID}:${VERSION}
